/**
 * Processed exercise images: grayscale silhouettes with transparent backgrounds.
 * Generated by scripts/process-exercise-images.js from free-exercise-db.
 *
 * For now, these are loaded locally from assets/exercises/.
 * To reduce app bundle size, host on a CDN and update BASE_URL.
 */

import { resolveImageId } from './exercise-images';

// For local dev / bundled assets, we use require().
// For production, swap to a CDN URL.
const USE_CDN = false;
const CDN_BASE = ''; // Set this to your CDN URL when ready

/**
 * Returns processed (silhouette) image URLs for an exercise.
 * Falls back to null if no mapping exists.
 */
export function getProcessedImageUrls(
  exerciseName: string,
): { start: string; end: string } | null {
  const id = resolveImageId(exerciseName);
  if (!id) return null;

  if (USE_CDN && CDN_BASE) {
    return {
      start: `${CDN_BASE}/${id}/0.png`,
      end: `${CDN_BASE}/${id}/1.png`,
    };
  }

  // For local: return the asset path (these need to be require()'d in the component)
  // Since we can't dynamically require, we'll use the raw GitHub approach for now
  // and apply the overlay filter in the component
  return null;
}
