const BASE_URL =
  'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises';

/**
 * Maps lowercase exercise name (from Forme app) to the free-exercise-db folder ID.
 * null means no matching exercise was found in the database.
 */
export const EXERCISE_IMAGE_MAP: Record<string, string | null> = {
  // ── CHEST ──
  'barbell bench press': 'Barbell_Bench_Press_-_Medium_Grip',
  'dumbbell bench press': 'Dumbbell_Bench_Press',
  'incline bench press': 'Barbell_Incline_Bench_Press_-_Medium_Grip',
  'dumbbell incline press': 'Incline_Dumbbell_Press',
  'decline bench press': 'Decline_Barbell_Bench_Press',
  'dumbbell decline press': 'Decline_Dumbbell_Bench_Press',
  'dumbbell chest fly': 'Dumbbell_Flyes',
  'incline dumbbell fly': 'Incline_Dumbbell_Flyes',
  'push-up': 'Pushups',
  'wide push-up': 'Push-Up_Wide',
  'diamond push-up': 'Push-Ups_-_Close_Triceps_Position',
  'decline push-up': 'Decline_Push-Up',
  'cable crossover': 'Cable_Crossover',
  'low cable fly': 'Low_Cable_Crossover',
  'machine chest press': 'Machine_Bench_Press',
  'pec deck': 'Reverse_Machine_Flyes',
  'svend press': 'Svend_Press',
  'dumbbell pullover': 'Bent-Arm_Dumbbell_Pullover',
  'floor press': 'Floor_Press',
  'smith machine bench press': 'Smith_Machine_Bench_Press',
  'smith machine incline press': 'Smith_Machine_Incline_Bench_Press',
  'plate squeeze press': null,
  'chest dip': 'Dips_-_Chest_Version',
  'cable chest press': 'Cable_Chest_Press',
  'incline cable fly': 'Incline_Cable_Flye',
  'hex press': 'Close-Grip_Dumbbell_Press',
  'close grip push-up': 'Push-Ups_-_Close_Triceps_Position',
  'archer push-up': null,
  'explosive push-up': 'Plyo_Push-up',

  // ── BACK ──
  'pull-up': 'Pullups',
  'chin-up': 'Chin-Up',
  'lat pulldown': 'Wide-Grip_Lat_Pulldown',
  'close grip lat pulldown': 'Close-Grip_Front_Lat_Pulldown',
  'barbell row': 'Bent_Over_Barbell_Row',
  'dumbbell row': 'One-Arm_Dumbbell_Row',
  'seated cable row': 'Seated_Cable_Rows',
  'deadlift': 'Barbell_Deadlift',
  'sumo deadlift': 'Sumo_Deadlift',
  'romanian deadlift': 'Romanian_Deadlift',
  't-bar row': 'T-Bar_Row_with_Handle',
  'pendlay row': 'Bent_Over_Barbell_Row',
  'meadows row': 'Bent_Over_One-Arm_Long_Bar_Row',
  'inverted row': 'Inverted_Row',
  'cable pullover': 'Straight-Arm_Pulldown',
  'straight arm pulldown': 'Straight-Arm_Pulldown',
  'machine row': 'Leverage_High_Row',
  'chest supported row': 'Dumbbell_Incline_Row',
  'single arm cable row': 'Seated_One-arm_Cable_Pulley_Rows',
  'rack pull': 'Rack_Pulls',
  'good morning': 'Good_Morning',
  'back extension': 'Hyperextensions_Back_Extensions',
  'seal row': null,
  'landmine row': 'Bent_Over_One-Arm_Long_Bar_Row',
  'wide grip pull-up': 'Wide-Grip_Rear_Pull-Up',
  'neutral grip pull-up': 'V-Bar_Pullup',
  'kneeling cable pulldown': 'Kneeling_High_Pulley_Row',
  'behind neck lat pulldown': 'Wide-Grip_Pulldown_Behind_The_Neck',
  'yates row': 'Reverse_Grip_Bent-Over_Rows',
  'smith machine row': 'Smith_Machine_Bent_Over_Row',
  'single arm lat pulldown': 'One_Arm_Lat_Pulldown',
  'cable face pull': 'Face_Pull',
  'snatch grip deadlift': 'Snatch_Deadlift',
  'single arm dumbbell row': 'One-Arm_Dumbbell_Row',
  'standing cable row': 'Elevated_Cable_Rows',

  // ── SHOULDERS ──
  'overhead press': 'Standing_Military_Press',
  'dumbbell shoulder press': 'Dumbbell_Shoulder_Press',
  'dumbbell lateral raise': 'Side_Lateral_Raise',
  'cable lateral raise': 'Cable_Seated_Lateral_Raise',
  'dumbbell front raise': 'Front_Dumbbell_Raise',
  'cable front raise': 'Front_Cable_Raise',
  'face pull': 'Face_Pull',
  'dumbbell rear delt fly': 'Dumbbell_Lying_Rear_Lateral_Raise',
  'arnold press': 'Arnold_Dumbbell_Press',
  'machine shoulder press': 'Leverage_Shoulder_Press',
  'barbell upright row': 'Upright_Barbell_Row',
  'dumbbell upright row': 'Standing_Dumbbell_Upright_Row',
  'reverse pec deck': 'Reverse_Machine_Flyes',
  'landmine press': 'Landmine_Linear_Jammer',
  'dumbbell shrug': 'Dumbbell_Shrug',
  'barbell shrug': 'Barbell_Shrug',
  'behind the neck press': 'Standing_Barbell_Press_Behind_Neck',
  'cable rear delt fly': 'Cable_Rear_Delt_Fly',
  'plate front raise': 'Front_Plate_Raise',
  'lu raise': null,
  'seated dumbbell lateral raise': 'Seated_Side_Lateral_Raise',
  'machine lateral raise': null,
  'bent over dumbbell lateral raise': 'Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench',
  'bradford press': 'Standing_Bradford_Press',
  'z press': null,
  'viking press': null,
  'dumbbell y raise': null,
  'kettlebell press': 'Alternating_Kettlebell_Press',
  'standing dumbbell front raise': 'Standing_Dumbbell_Straight-Arm_Front_Delt_Raise_Above_Head',
  'seated dumbbell front raise': 'Front_Dumbbell_Raise',
  'single arm cable lateral raise': 'One-Arm_Side_Laterals',
  'single arm cable front raise': 'Front_Cable_Raise',
  'standing dumbbell lateral raise': 'Side_Lateral_Raise',
  'seated dumbbell shoulder press': 'Seated_Dumbbell_Press',
  'standing dumbbell shoulder press': 'Standing_Dumbbell_Press',
  'single arm cable rear delt fly': 'Cable_Rear_Delt_Fly',
  'single arm dumbbell shoulder press': 'Dumbbell_One-Arm_Shoulder_Press',

  // ── BICEPS ──
  'barbell curl': 'Barbell_Curl',
  'dumbbell curl': 'Dumbbell_Bicep_Curl',
  'hammer curl': 'Hammer_Curls',
  'preacher curl': 'Preacher_Curl',
  'concentration curl': 'Concentration_Curls',
  'incline dumbbell curl': 'Incline_Dumbbell_Curl',
  'cable curl': 'Standing_Biceps_Cable_Curl',
  'spider curl': 'Spider_Curl',
  'ez bar curl': 'EZ-Bar_Curl',
  'reverse curl': 'Reverse_Barbell_Curl',
  'bayesian curl': null,
  'cable hammer curl': 'Cable_Hammer_Curls_-_Rope_Attachment',
  'zottman curl': 'Zottman_Curl',
  '21s bicep curl': null,
  'cross body hammer curl': 'Cross_Body_Hammer_Curl',
  'drag curl': 'Drag_Curl',
  'machine preacher curl': 'Machine_Preacher_Curls',
  'cable preacher curl': 'Cable_Preacher_Curl',
  'waiter curl': null,
  'overhead cable curl': 'Overhead_Cable_Curl',
  'ez bar preacher curl': 'Preacher_Curl',
  'incline hammer curl': 'Incline_Hammer_Curls',
  'single arm dumbbell curl': 'Dumbbell_Alternate_Bicep_Curl',
  'single arm cable curl': 'Standing_One-Arm_Cable_Curl',
  'seated dumbbell curl': 'Seated_Dumbbell_Curl',
  'standing dumbbell curl': 'Dumbbell_Bicep_Curl',
  'standing cable curl': 'Standing_Biceps_Cable_Curl',
  'wrist curl': 'Palms-Up_Barbell_Wrist_Curl_Over_A_Bench',
  'reverse wrist curl': 'Palms-Down_Wrist_Curl_Over_A_Bench',
  'farmer carry': 'Farmers_Walk',

  // ── TRICEPS ──
  'tricep pushdown': 'Triceps_Pushdown',
  'skull crusher': 'EZ-Bar_Skullcrusher',
  'tricep dip': 'Dips_-_Triceps_Version',
  'close grip bench press': 'Close-Grip_Barbell_Bench_Press',
  'dumbbell overhead tricep extension': 'Standing_Dumbbell_Triceps_Extension',
  'cable overhead extension': 'Cable_Rope_Overhead_Triceps_Extension',
  'dumbbell tricep kickback': 'Tricep_Dumbbell_Kickback',
  'rope pushdown': 'Triceps_Pushdown_-_Rope_Attachment',
  'single arm pushdown': 'Cable_One_Arm_Tricep_Extension',
  'dip machine': 'Dip_Machine',
  'bench dip': 'Bench_Dips',
  'jm press': 'JM_Press',
  'lying tricep extension': 'Lying_Triceps_Press',
  'french press': 'Lying_Close-Grip_Barbell_Triceps_Extension_Behind_The_Head',
  'cable tricep kickback': null,
  'diamond dip': 'Dips_-_Triceps_Version',
  'single arm tricep pushdown': 'Cable_One_Arm_Tricep_Extension',
  'single arm overhead tricep extension': 'Dumbbell_One-Arm_Triceps_Extension',
  'seated overhead tricep extension': 'Seated_Triceps_Press',

  // ── LEGS ──
  'squat': 'Barbell_Full_Squat',
  'barbell squat': 'Barbell_Squat',
  'front squat': 'Front_Barbell_Squat',
  'leg press': 'Leg_Press',
  'hack squat': 'Hack_Squat',
  'lunge': 'Dumbbell_Lunges',
  'walking lunge': 'Barbell_Walking_Lunge',
  'reverse lunge': 'Dumbbell_Rear_Lunge',
  'bulgarian split squat': 'Split_Squats',
  'leg extension': 'Leg_Extensions',
  'goblet squat': 'Goblet_Squat',
  'step-up': 'Dumbbell_Step_Ups',
  'wall sit': null,
  'sissy squat': 'Weighted_Sissy_Squat',
  'single leg press': 'Leg_Press',
  'box squat': 'Box_Squat',
  'smith machine squat': 'Smith_Machine_Squat',
  'belt squat': null,
  'pistol squat': 'Kettlebell_Pistol_Squat',
  'jefferson squat': 'Jefferson_Squats',
  'zercher squat': 'Zercher_Squats',
  'leg curl': 'Lying_Leg_Curls',
  'seated leg curl': 'Seated_Leg_Curl',
  'stiff leg deadlift': 'Stiff-Legged_Barbell_Deadlift',
  'romanian deadlift (dumbbell)': 'Stiff-Legged_Dumbbell_Deadlift',
  'single leg romanian deadlift': 'Kettlebell_One-Legged_Deadlift',
  'nordic hamstring curl': 'Natural_Glute_Ham_Raise',
  'glute ham raise': 'Glute_Ham_Raise',
  'cable pull-through': 'Pull_Through',
  'hip thrust': 'Barbell_Hip_Thrust',
  'barbell hip thrust': 'Barbell_Hip_Thrust',
  'glute bridge': 'Barbell_Glute_Bridge',
  'single leg glute bridge': 'Single_Leg_Glute_Bridge',
  'cable kickback': 'One-Legged_Cable_Kickback',
  'donkey kick': 'Glute_Kickback',
  'fire hydrant': null,
  'sumo squat': 'Plie_Dumbbell_Squat',
  'frog pump': null,
  'calf raise': 'Standing_Calf_Raises',
  'seated calf raise': 'Seated_Calf_Raise',
  'single leg calf raise': 'Dumbbell_Seated_One-Leg_Calf_Raise',
  'donkey calf raise': 'Donkey_Calf_Raises',
  'smith machine calf raise': 'Smith_Machine_Calf_Raise',
  'leg press calf raise': 'Calf_Press_On_The_Leg_Press_Machine',
  'adductor machine': 'Thigh_Adductor',
  'abductor machine': 'Thigh_Abductor',
  'cable hip adduction': 'Cable_Hip_Adduction',
  'cable hip abduction': null,
  'lateral band walk': 'Monster_Walk',
  'copenhagen plank': null,
  'narrow stance squat': 'Narrow_Stance_Squats',
  'wide stance squat': 'Wide_Stance_Barbell_Squat',
  'pause squat': 'Barbell_Full_Squat',
  'safety bar squat': null,
  'curtsy lunge': null,
  'deficit lunge': null,
  'split squat': 'Split_Squats',
  'lateral lunge': 'Barbell_Side_Split_Squat',
  'pendulum squat': null,
  'v squat': null,
  'narrow stance leg press': 'Narrow_Stance_Leg_Press',
  'wide stance leg press': 'Leg_Press',
  'barbell calf raise': 'Standing_Barbell_Calf_Raise',
  'dumbbell lunge': 'Dumbbell_Lunges',
  'dumbbell step-up': 'Dumbbell_Step_Ups',
  'barbell glute bridge': 'Barbell_Glute_Bridge',
  'single leg leg press': 'Leg_Press',
  'leg press (high foot)': 'Leg_Press',
  'leg press (low foot)': 'Leg_Press',
  'machine hip thrust': null,
  'single leg leg extension': 'Single-Leg_Leg_Extension',
  'single leg leg curl': 'Seated_Leg_Curl',
  'standing calf raise': 'Standing_Calf_Raises',

  // ── CORE ──
  'plank': 'Plank',
  'side plank': 'Side_Bridge',
  'crunch': 'Crunches',
  'reverse crunch': 'Reverse_Crunch',
  'russian twist': 'Russian_Twist',
  'hanging leg raise': 'Hanging_Leg_Raise',
  'hanging knee raise': 'Knee_Hip_Raise_On_Parallel_Bars',
  'cable crunch': 'Cable_Crunch',
  'mountain climber': 'Mountain_Climbers',
  'bicycle crunch': 'Cross-Body_Crunch',
  'dead bug': 'Dead_Bug',
  'bird dog': null,
  'ab wheel rollout': 'Ab_Roller',
  'pallof press': 'Pallof_Press',
  'woodchop': 'Standing_Cable_Wood_Chop',
  'reverse woodchop': 'Standing_Cable_Lift',
  'v-up': null,
  'toe touch': 'Toe_Touchers',
  'flutter kick': 'Flutter_Kicks',
  'leg raise': 'Flat_Bench_Lying_Leg_Raise',
  'sit-up': 'Sit-Up',
  'dragon flag': null,
  'ab crunch machine': 'Ab_Crunch_Machine',
  'decline sit-up': 'Decline_Crunch',
  'hollow body hold': null,
  'l-sit': null,
  'windshield wiper': null,
  'suitcase carry': null,
  'weighted plank': null,
  'weighted crunch': 'Weighted_Crunches',
  'cable pallof press': 'Pallof_Press',
  'landmine rotation': 'Landmine_180s',
  'farmer walk': 'Farmers_Walk',
  'turkish get-up (core)': 'Kettlebell_Turkish_Get-Up_Squat_style',
  'stability ball crunch': 'Exercise_Ball_Crunch',
  'medicine ball slam': 'Overhead_Slam',
  'plank shoulder tap': null,
  'body saw': null,
  'stir the pot': null,
  'copenhagen side plank': null,

  // ── CARDIO ──
  'incline treadmill walk': 'Walking_Treadmill',
  'brisk walk': 'Walking_Treadmill',
  'jump rope': 'Rope_Jumping',
  'rowing machine': 'Rowing_Stationary',
  'stair climber': 'Stairmaster',
  'battle ropes': 'Battling_Ropes',
  'box jump': 'Box_Jump_Multiple_Response',
  'burpee': null,
  'jumping jack': null,
  'high knees': null,
  'kettlebell swing': 'One-Arm_Kettlebell_Swings',
  'assault bike': 'Air_Bike',
  'sprints': 'Wind_Sprints',
  'sled push': 'Sled_Push',
  'sled pull': 'Sled_Drag_-_Harness',
  'bear crawl': null,
  'elliptical': 'Elliptical_Trainer',
  'cycling': 'Bicycling_Stationary',
  'swimming': null,
  'skater jump': 'Side_To_Side_Box_Shuffle',
  'tuck jump': 'Knee_Tuck_Jump',
  'broad jump': 'Standing_Long_Jump',
  'hill sprint': 'Running_Treadmill',
  'prowler push': 'Prowler_Sprint',
  'ski erg': null,
  'versa climber': null,
  'jacob ladder': null,
  'shadow boxing': null,
  'jump squat': 'Freehand_Jump_Squat',

  // ── BANDS ──
  'band pull-apart': 'Band_Pull_Apart',
  'band row': 'Back_Flyes_-_With_Bands',
  'band squat': 'Squats_-_With_Bands',
  'band chest press': 'Cross_Over_-_With_Bands',
  'band bicep curl': null,
  'band tricep extension': 'Band_Skull_Crusher',
  'band face pull': null,
  'band lateral raise': 'Lateral_Raise_-_With_Bands',
  'band good morning': 'Band_Good_Morning',
  'band hip thrust': null,
  'band leg curl': 'Seated_Band_Hamstring_Curl',
  'band deadlift': null,

  // ── FULL BODY ──
  'clean and press': 'Clean_and_Press',
  'thruster': 'Kettlebell_Thruster',
  'man maker': null,
  'turkish get-up': 'Kettlebell_Turkish_Get-Up_Squat_style',
  'power clean': 'Power_Clean',
  'snatch': 'Snatch',
  'hang clean': 'Hang_Clean',
  'push press': 'Push_Press',
  'clean': 'Clean',
  'muscle-up': 'Muscle_Up',
  'wall ball': null,
  'dumbbell snatch': null,
  'kettlebell clean': 'One-Arm_Kettlebell_Clean',
  'kettlebell snatch': 'One-Arm_Kettlebell_Snatch',
  'devil press': null,
  'barbell complex': null,
  'bear complex': null,
  'hang snatch': 'Hang_Snatch',
  'sumo deadlift high pull': 'Kettlebell_Sumo_High_Pull',
};

/**
 * Returns both start and end position image URLs for an exercise, or null if
 * no mapping exists.
 */
export function getExerciseImageUrls(
  name: string,
): { start: string; end: string } | null {
  const id = EXERCISE_IMAGE_MAP[name.toLowerCase()];
  if (!id) return null;
  return {
    start: `${BASE_URL}/${id}/0.jpg`,
    end: `${BASE_URL}/${id}/1.jpg`,
  };
}

/** Returns the start-position image URL, or null. */
export function getExerciseStartImage(name: string): string | null {
  const id = EXERCISE_IMAGE_MAP[name.toLowerCase()];
  if (!id) return null;
  return `${BASE_URL}/${id}/0.jpg`;
}

/** Returns the end-position image URL, or null. */
export function getExerciseEndImage(name: string): string | null {
  const id = EXERCISE_IMAGE_MAP[name.toLowerCase()];
  if (!id) return null;
  return `${BASE_URL}/${id}/1.jpg`;
}
