// Shared exercise data — used by both planned workouts and quick create
// Seeded from Wger exercise database categories + comprehensive exercise lists

export const BODYWEIGHT_KEYWORDS = [
  'push-up', 'push up', 'pushup', 'pull-up', 'pull up', 'pullup',
  'plank', 'burpee', 'jumping jack', 'bodyweight', 'dip', 'crunch',
  'sit-up', 'situp', 'mountain climber', 'jump rope', 'brisk walk',
  'lunge', 'pike', 'superman', 'glute bridge', 'calf raise',
  'inverted row', 'chin-up', 'chin up', 'pistol squat', 'box jump',
];

export function isBodyweightExercise(name: string): boolean {
  const lower = name.toLowerCase();
  return BODYWEIGHT_KEYWORDS.some((kw) => lower.includes(kw));
}

// Exercise instructions lookup — actionable coaching cues (2-3 sentences max)
export const EXERCISE_INSTRUCTIONS: Record<string, string> = {
  // Chest
  'barbell bench press': 'Pin your shoulder blades together like you\'re cracking a walnut between them. Drive your feet into the floor and lower the bar to your nipple line. Press up in a slight arc back toward your face.',
  'dumbbell bench press': 'Set your shoulder blades down and back like you\'re tucking them into your back pockets. Lower the dumbbells until you feel a deep stretch across your chest, elbows at 45 degrees. Press up and squeeze the dumbbells together at the top like you\'re giving a bear hug.',
  'incline bench press': 'Dig your upper back into the bench and arch just enough to slide a fist under your lower back. Think about pressing yourself away from the bar, not the bar away from you. The bar should touch your upper chest just below your collarbone.',
  'dumbbell incline press': 'Keep your chest puffed up like you\'re showing off a medal the entire time. Lower until your elbows drop just below the bench for a full stretch. Press up and angle the dumbbells slightly inward like you\'re pouring two pitchers together.',
  'decline bench press': 'Lock your shoulder blades down tight — they shouldn\'t move the entire set. Touch the bar to your lower chest right at the base of your sternum. Press straight up and think about bending the bar into a U-shape with your hands.',
  'dumbbell decline press': 'Squeeze your shoulder blades together and keep your chest high even on the decline. Lower slow enough that you could pause at any point. Drive up powerfully, imagining you\'re pushing someone off you.',
  'chest fly': 'Pretend you\'re hugging a giant tree — keep that same arm curve the whole time. Open wide until you feel a stretch like your chest is being pulled apart. Squeeze back together like you\'re clapping in slow motion.',
  'incline dumbbell fly': 'Keep a slight bend in your elbows locked in like a cast — don\'t let it change. Open your arms until you feel your chest fibers stretching like a rubber band. Bring the dumbbells together overhead and try to touch your inner biceps together.',
  'push-up': 'Screw your hands into the floor like you\'re tightening jar lids, elbows track at 45 degrees. Lower until your chest kisses the floor, not your hips. Push the ground away from you and finish with your shoulder blades spread wide.',
  'wide push-up': 'Set your hands wide enough that your forearms are vertical at the bottom. Think about pulling yourself down to the floor like a controlled fall. Push back up and squeeze your chest like you\'re trying to crack a walnut between your pecs.',
  'diamond push-up': 'Make a diamond with your index fingers and thumbs right under your sternum. Keep your elbows tight to your ribs like you\'re squeezing tennis balls in your armpits. You should feel this burn deep in your triceps and inner chest.',
  'decline push-up': 'The higher your feet, the more you\'ll hit upper chest — find the angle that burns there. Keep your body rigid like a steel beam from ankles to head. Don\'t let your hips sag; if they do, your set is over.',
  'cable crossover': 'Take a small step forward and lean in like you\'re about to take off running. Sweep your arms together in a big arc like you\'re scooping up a beach ball. Squeeze so hard at the bottom that your hands almost overlap.',
  'low cable fly': 'Start with your hands low and sweep up and together like you\'re tossing confetti into the air. Keep your arms almost straight — bend only enough to protect your elbows. Squeeze at the top like you\'re trying to press your palms through each other.',
  'machine chest press': 'Press your back flat into the pad and set your shoulder blades before you start. Drive the handles forward like you\'re shoving a heavy door open. Let it come back slow enough that you feel your chest loading up like a spring.',
  'pec deck': 'Sit tall and think about leading with your elbows, not your hands. Bring the pads together like you\'re closing a book in front of your face. Open up only until you feel a stretch — don\'t let your shoulders roll forward.',
  'svend press': 'Squeeze the plates together so hard your chest starts shaking before you even move. Press straight out at chest height like you\'re showing someone how hard you can push. Keep constant crushing pressure — the moment you relax, you lose the exercise.',
  'dumbbell pullover': 'Lie with just your upper back across the bench, hips dropped low. Reach the dumbbell back behind your head until you feel your lats and chest stretch like taffy. Pull it back over with straight arms, feeling your chest and lats fight over the work.',
  'floor press': 'The floor is your safety net — let your triceps settle onto it briefly each rep. Press up explosively like you\'re throwing the weight at the ceiling. This is all about lockout power, so squeeze your triceps hard at the top.',
  // Back
  'pull-up': 'Imagine you\'re trying to bend the bar into a horseshoe — that fires your lats instantly. Pull your chest to the bar, not just your chin over it. Lower slow and controlled until your arms are completely straight, earning every inch.',
  'chin-up': 'Grip underhand and think about driving your elbows down into your back pockets. Pull until your chin clears the bar and you feel your biceps and lats working together. Lower all the way to dead hang — no half reps.',
  'lat pulldown': 'Lean back just slightly and puff your chest up to meet the bar. Pull the bar to your upper chest by driving your elbows toward your hips, not behind you. Let the bar stretch you all the way up — feel your lats lengthen like a rubber band at the top.',
  'close grip lat pulldown': 'Use a neutral or V-grip handle and think about pulling from your armpits. Drive your elbows straight down past your ribcage and squeeze your back like you\'re pinching a pencil between your shoulder blades. Let the weight stretch you fully at the top — that\'s where the growth happens.',
  'barbell row': 'Hinge over until your torso is nearly parallel to the floor and brace your core like you\'re about to take a punch. Row the bar to your belly button, leading with your elbows like you\'re elbowing someone behind you. If your torso is swinging up to meet the bar, the weight is too heavy.',
  'dumbbell row': 'Think about pulling with your elbow toward your back pocket. Let the dumbbell hang straight down at the start for a full stretch. Squeeze your shoulder blade in at the top like you\'re starting a lawnmower.',
  'seated cable row': 'Sit tall and start each rep by pulling your shoulder blades together before your arms even bend. Drive your elbows past your ribcage and imagine you\'re trying to touch them together behind your back. Return slow and let the cable pull your shoulders forward for a deep stretch.',
  'deadlift': 'Push the floor away with your legs like a leg press — the bar just happens to be in your hands. Keep the bar so close to your body it scrapes your shins. Lock out by driving your hips into the bar, standing tall and proud.',
  'sumo deadlift': 'Spread your feet wide, point your toes out, and shove your knees over your pinky toes. Drop your hips and grip inside your legs — think about pushing the floor apart with your feet. Drive up by squeezing your glutes like you\'re trying to crack a walnut between them.',
  'romanian deadlift': 'Push your hips back like you\'re closing a car door with your butt. Keep the bar glued to your thighs — if it drifts forward, your lower back takes over. You should feel your hamstrings screaming for a stretch by the bottom.',
  't-bar row': 'Brace your core like someone\'s about to punch your gut and hinge forward. Pull the handle into your belly button, squeezing your elbows tight to your sides. If you can\'t hold the top for a one-count squeeze, lighten the weight.',
  'pendlay row': 'Let the bar rest dead on the floor between every rep — no bounce, no momentum. Explode it to your lower chest like you\'re trying to dent your ribcage. This is a power movement, so be violent off the floor but controlled at the top.',
  'meadows row': 'Stand perpendicular to the landmine and stagger your stance for a huge stretch. Pull the bar to your hip like you\'re ripping a weed out of the ground. Let it stretch your lat at the bottom until you feel the muscle wringing out.',
  'inverted row': 'Keep your body rigid like a plank — your hips shouldn\'t sag or pike at any point. Pull your chest to the bar by driving your elbows toward the ground. The straighter your body angle, the harder this gets, so adjust your foot position to find the right challenge.',
  'cable pullover': 'Stand far enough back to feel tension at the start with arms overhead. Pull down in a big sweeping arc, keeping your arms nearly straight. Think about pushing your chest out and driving the bar to your thighs with your lats, not your arms.',
  'straight arm pulldown': 'Lock your arms almost straight and hinge forward slightly at the hips. Pull the bar to your thighs using only your lats — your arms are just hooks. Squeeze for a beat at the bottom and feel your lats contract like you\'re flaring a cobra hood.',
  'machine row': 'Press your chest firmly into the pad — if your chest lifts off, you\'re using momentum. Pull the handles to your ribcage and imagine trying to elbow someone standing behind you. Return slowly and let the weight stretch your back open between reps.',
  'chest supported row': 'Let gravity work for you — your chest on the bench means your lower back gets a break. Row to your ribcage and hold the squeeze for a full second. Let the dumbbells hang at the bottom until you feel your shoulder blades separate.',
  'single arm cable row': 'Stagger your feet and let your working shoulder reach forward at the start for extra range. Pull to your hip and rotate your torso slightly, like you\'re opening a door. Fight the weight back slowly — the negative is where you build thickness.',
  'rack pull': 'Set the pins at knee height and load this heavier than your deadlift. Grip it, brace hard, and drive your hips through the bar like you\'re trying to push it forward. This is all about building a vice-grip back and monster traps.',
  'good morning': 'The bar sits on your traps, not your neck — push your hips back like someone tied a rope to your waist. Your back stays flat as a board while your hamstrings load up like a spring. Stand up by driving your hips forward, not by lifting your chest.',
  'back extension': 'Don\'t think about lifting your torso — think about squeezing your glutes and hamstrings to pull yourself up. Pause at the top and feel your entire posterior chain working as a team. If you\'re feeling this in your lower back more than your glutes, you\'re hyperextending.',
  'seal row': 'Lying face down takes all cheating off the table — you can\'t use momentum here. Row the dumbbells straight up to your ribcage and crush your shoulder blades together. Lower until your arms are fully straight and you feel a deep stretch in your lats.',
  'landmine row': 'Hinge over the bar with a flat back and brace like you\'re wearing a weightlifting belt. Row to your chest and think about arcing your elbows up and back. Control the lowering — let the stretch at the bottom be the reward.',
  // Shoulders
  'overhead press': 'Stack the bar on your collarbone and take a big belly breath before you press. Drive the bar straight up by pushing your head through the window your arms create. If your lower back arches excessively, brace harder or use less weight.',
  'dumbbell shoulder press': 'Start with the dumbbells at ear height like you\'re a goalpost. Press up and slightly inward so they nearly touch overhead. Lower until your elbows are just below your shoulders — going lower risks your rotator cuff.',
  'lateral raise': 'Lead with your elbows like you\'re pouring two pitchers of water in slow motion. Stop at shoulder height — going higher just invites your traps to take over. Lower like you\'re pressing down through wet cement.',
  'cable lateral raise': 'Stand far enough from the cable that you feel tension even at the bottom. Raise with a slight forward lean, pinky side up, like you\'re pouring out a drink. Don\'t let the cable yank your arm down — control every inch of the return.',
  'front raise': 'Think about reaching forward and up like you\'re handing something to a tall person. Stop at eye level — any higher and your traps steal the work. If you\'re swinging or leaning back, the weight is too heavy.',
  'face pull': 'Pull the rope to your face and finish by spreading your hands apart like you\'re flexing a double bicep pose. Squeeze your rear delts and hold for a beat — this is about control, not power. Your elbows should end up high and wide, not pinned to your sides.',
  'rear delt fly': 'Hinge forward and let your arms hang like wet noodles before you start. Raise out to the sides leading with your pinkies like you\'re trying to fly backward. If you feel this in your traps more than the back of your shoulders, lighten up.',
  'arnold press': 'Start with the dumbbells in front of your face, palms toward you. Rotate and press in one smooth motion like you\'re opening two revolving doors. The rotation is what makes this special — don\'t rush through it.',
  'machine shoulder press': 'Press your back flat into the pad and resist the urge to arch as it gets hard. Drive the handles up like you\'re trying to punch the ceiling. Lower until you feel a stretch in your shoulders, then reverse — don\'t bounce off the bottom.',
  'barbell upright row': 'Pull the bar up your body like you\'re zipping up a jacket. Lead with your elbows and stop when they reach shoulder height. Keep the bar close — if it drifts forward, your front delts do all the work.',
  'dumbbell upright row': 'Lead with your elbows like a marionette being pulled up by strings. Let the dumbbells drift slightly away from your body for a better shoulder contraction. Stop when your elbows hit shoulder height to protect your rotator cuffs.',
  'cable front raise': 'Face away from the machine and raise the handle to eye level with a straight arm. Think about pushing your fist forward and up, not just lifting. Lower with control — this is where the front delt really works.',
  'reverse pec deck': 'Set the handles at shoulder height and lead the movement with your elbows, not your hands. Open up until you feel your rear delts and upper back squeeze like you\'re trying to touch your shoulder blades together. Don\'t swing — if the weight stack slams, slow down.',
  'landmine press': 'Press up and out at a 45-degree angle like you\'re punching the ceiling in front of you. Brace your core hard — one side is loaded so your obliques have to fight to keep you straight. This is easier on your shoulders than a straight overhead press, so push hard.',
  'dumbbell shrug': 'Shrug straight up toward your ears like you\'re saying "I don\'t know" as dramatically as possible. Hold the top for a two-count and feel your traps cramp up. Don\'t roll your shoulders — that\'s a myth and it\'s rough on your joints.',
  'barbell shrug': 'Grip the bar just outside your hips and stand tall. Shrug straight up like you\'re trying to touch your ears with your shoulders. Hold the squeeze at the top — if you can\'t hold it for a second, the weight is too heavy.',
  'behind the neck press': 'Use a wide grip and only lower to the top of your ears — going deeper is an injury waiting to happen. Press straight up and keep your head pushed slightly forward out of the bar path. If this hurts your shoulders at all, switch to a front press immediately.',
  'cable rear delt fly': 'Cross the cables and grab opposite handles at face height. Pull apart like you\'re trying to rip a phone book in half. Squeeze your rear delts at the end position — you should feel the burn right behind your shoulders.',
  'plate front raise': 'Grip a plate at 3 and 9 o\'clock and raise it to eye level. Think about pushing the plate away from you as you lift, not just going up. Your front delts should be on fire by rep 8 — if not, go slower.',
  'band pull-apart': 'Hold the band at shoulder width with arms straight out like a zombie. Pull apart by squeezing your shoulder blades together until the band touches your chest. This is a prehab staple — do it slow and feel every fiber working.',
  'lu raise': 'Start with a lateral raise to shoulder height, then without pausing, press overhead. Reverse the exact same path on the way down. Use light weight — this burns like nothing else because your delts never get a break.',
  // Arms — Biceps
  'barbell curl': 'Glue your elbows to your ribcage — they\'re bolted there for the entire set. Curl the bar up and imagine you\'re trying to touch your shoulders with your pinkies. Lower for a slow three-count; the eccentric is where biceps grow.',
  'dumbbell curl': 'Start with your palms facing your legs and rotate as you curl, like you\'re turning a doorknob. Squeeze at the top like you\'re flexing for a photo. If your elbows drift forward, you\'re using your front delts to cheat.',
  'hammer curl': 'Keep your palms facing each other the whole time like you\'re holding two hammers. Drive your thumbs toward your shoulders and squeeze your forearms at the top. This hits your brachialis — the muscle that makes your arms look thick from the side.',
  'preacher curl': 'Drape your arms over the pad and keep your armpits glued to the top edge. Curl up and squeeze so hard your biceps cramp, then lower slowly — don\'t just let it drop. Stop just short of full extension at the bottom to keep tension on the muscle.',
  'concentration curl': 'Brace your elbow against your inner thigh and let the dumbbell hang for a full stretch. Curl with laser focus on the bicep — you should see it bunch up. This is your ego-check exercise; if you\'re swinging, the weight is too heavy.',
  'incline dumbbell curl': 'Let your arms hang straight down like dead weight to start — that stretch is the whole point. Curl without letting your elbows drift forward, keeping your upper arms vertical. This hits the long head of your bicep that gives you that peak.',
  'cable curl': 'Step back from the cable so there\'s tension even at the bottom. Curl up and squeeze like you\'re trying to make a muscle for a kid. Lower slow and steady — the constant cable tension is what makes this better than free weights for a pump.',
  'spider curl': 'Drape your arms over the vertical side of a preacher bench so they hang straight down. Curl up and squeeze your biceps at the top until they cramp. Gravity is fighting you the hardest at the top — that\'s where most curls are easiest, so this fills the gap.',
  'ez bar curl': 'The angled grip saves your wrists — grip where it feels natural and comfortable. Keep your elbows pinned and curl the bar to your chest like you\'re compressing a spring. Lower for a full two-count or you\'re leaving gains on the table.',
  'reverse curl': 'Grip the bar overhand and keep your wrists locked straight — no curling them. This will burn your forearms and the outside of your upper arm like nothing else. Use lighter weight than regular curls; your ego will survive.',
  'bayesian curl': 'Face away from the cable with your arm stretched behind you at the start. Curl forward and up, keeping your elbow pinned behind your torso the whole time. This extreme stretch position is what makes the exercise special — don\'t cheat it short.',
  'cable hammer curl': 'Use the rope and keep your thumbs pointing up the entire time. Curl up and pull the rope apart slightly at the top for an extra squeeze. This builds the meaty part of your forearm and the outside of your bicep.',
  'zottman curl': 'Curl up with palms facing you like a normal curl, then rotate to palms-down at the top. Lower slowly with palms down — this overloads the eccentric for your forearms. Rotate back to palms-up at the bottom and repeat.',
  '21s bicep curl': 'Do 7 reps from the bottom to halfway, 7 from halfway to the top, then 7 full reps — no rest between. Your biceps should feel like they\'re filled with battery acid by the second phase. Use lighter weight than you think; this is about the burn, not the load.',
  // Arms — Triceps
  'tricep pushdown': 'Lock your elbows to your sides like they\'re in a cast. Push down until your arms are arrow-straight and squeeze your triceps like you\'re flexing for someone. If your elbows flare forward, the weight is too heavy.',
  'skull crusher': 'Keep your upper arms perfectly vertical — they should point straight at the ceiling the whole time. Lower the bar toward your forehead like you\'re scared of it, slow and controlled. Press back up by straightening only at the elbow, nothing else moves.',
  'tricep dip': 'Lean your torso slightly forward for chest focus, or stay upright to fry your triceps. Lower until your upper arms are parallel to the floor — no deeper or your shoulders will hate you. Drive up hard and lock out completely at the top.',
  'close grip bench press': 'Grip the bar shoulder-width and tuck your elbows tight against your ribs on the way down. Touch the bar to your lower chest and explode up, thinking about straightening your arms. Your triceps should be doing most of the work — if your chest is pumped, widen your grip.',
  'overhead tricep extension': 'Keep your elbows pointed straight at the ceiling, hugging close to your head. Lower the weight behind your head until you feel a deep stretch in your triceps. Extend up and squeeze like you\'re trying to lock a door above your head.',
  'cable overhead extension': 'Face away from the cable with the rope behind your head and take a big step forward. Extend your arms forward and up until they\'re completely straight. Your elbows are the hinge — everything else stays frozen.',
  'tricep kickback': 'Pin your upper arm parallel to the floor and don\'t let it move one inch. Straighten your arm back and squeeze your tricep at the end like you\'re trying to make it cramp. If your elbow drops, you\'re cheating — use a lighter weight.',
  'rope pushdown': 'Push down and spread the rope apart at the bottom like you\'re ripping it in two. Squeeze your triceps at full extension and hold for a beat. Let it come back up only to 90 degrees — going higher shifts tension to your shoulders.',
  'single arm pushdown': 'Work one arm at a time to expose any imbalance. Push down and twist your wrist slightly outward at the bottom for peak contraction. Use your free hand on your elbow to keep it from drifting.',
  'dip machine': 'Press the handles down and focus on straightening your arms completely. Squeeze your triceps hard at the bottom like you\'re flexing them. Let the weight pull your arms back up slowly — that\'s the part that builds size.',
  'bench dip': 'Walk your feet far enough out that your butt clears the bench when you lower. Dip until your upper arms are parallel to the floor, no deeper. If you feel shoulder strain, bring your feet closer to reduce the load.',
  'jm press': 'This is a hybrid between a skull crusher and a close grip bench — the bar comes to your chin or upper chest. Keep your elbows pointed forward, not flared. Lower slowly and feel the tricep stretch before pressing back to lockout.',
  // Arms — Forearms
  'wrist curl': 'Let the bar roll down to your fingertips at the bottom, then curl your fingers closed and flex your wrists up. This double motion hits both your finger flexors and wrist flexors. Use a weight you can do 15+ reps with — forearms respond to volume.',
  'reverse wrist curl': 'Forearms flat on your thighs, palms facing down, and curl your knuckles toward the ceiling. Use half the weight you\'d use for regular wrist curls — these muscles are small but important. Slow reps build wrist stability that carries over to every other lift.',
  'farmer carry': 'Grab the heaviest dumbbells you can hold and walk like you own the place. Shoulders packed down, chest proud, grip crushing. When your grip starts slipping, that\'s when the real work begins.',
  // Legs — Quads
  'squat': 'Screw your feet into the floor and spread the ground apart. Sit back like there\'s a chair behind you, chest stays proud. Drive up by pushing the floor away from you.',
  'barbell squat': 'Screw your feet into the floor and create torque by spreading the ground apart with your feet. Take a big belly breath and sit back like there\'s a chair you\'re lowering onto. Drive up by pushing the earth away — your chest stays tall or the rep doesn\'t count.',
  'front squat': 'Elbows up so high you could balance a tray of drinks on your arms. Sit straight down between your hips, keeping your torso as vertical as a wall. If your elbows drop, the bar rolls — fight to keep them pointed at the wall in front of you.',
  'leg press': 'Place your feet hip-width and push through your whole foot — not just your toes. Lower the sled until your knees nearly touch your chest for full range. Press up but stop just before lockout to keep constant tension on your quads.',
  'hack squat': 'Shoulder pads on, feet slightly forward on the platform. Lower until your thighs are parallel and you feel your quads loading like coiled springs. Press up without locking your knees — keep the tension relentless.',
  'lunge': 'Step far enough forward that your shin stays vertical at the bottom. Drop your back knee like you\'re kneeling to propose. Push back up through your front heel — if you feel it in your front knee, your step is too short.',
  'walking lunge': 'Take long, deliberate strides like you\'re walking through deep mud. Keep your torso upright — don\'t lean forward like you\'re chasing something. Each step should feel like a separate squat on one leg.',
  'reverse lunge': 'Step back and straight down like you\'re lowering into an elevator. Your front shin stays perfectly vertical — that\'s the key to protecting your knee. Drive back to standing through your front heel.',
  'bulgarian split squat': 'Rear foot up on a bench, front foot far enough forward that your knee doesn\'t pass your toes. Sink straight down like an elevator, feeling your front quad stretch under load. Drive up through your front heel — if your rear leg is doing the work, step further forward.',
  'leg extension': 'Squeeze your quads at the top like you\'re trying to straighten your legs through a locked door. Hold for a one-count at full extension and feel the burn right above your kneecap. Lower slow — this exercise is about the squeeze, not the weight.',
  'goblet squat': 'Hold the dumbbell at your chest like you\'re protecting a precious gem. Let your elbows push your knees apart at the bottom. Sit deep and proud, then stand by driving the floor away.',
  'step-up': 'Plant your whole foot on the box and drive through your heel like you\'re stomping a bug. Don\'t push off your back foot — make the working leg do everything. If you catch yourself bouncing off the ground, lower the box.',
  'wall sit': 'Slide down until your thighs are truly parallel — most people cheat this high. Push your entire back flat against the wall and press through your heels. When it starts burning like fire, that\'s when the exercise begins.',
  'sissy squat': 'Hold something for balance and lean back as your knees push way forward. Lower until you feel an insane stretch in your quads above your kneecap. Rise back up slow — this is one of the hardest bodyweight quad exercises for a reason.',
  'single leg press': 'Place one foot in the center of the platform and lower slow. Press up through your whole foot, not just your toes. This exposes imbalances between legs, so start with your weaker side.',
  'box squat': 'Sit back to the box like you\'re sitting on a cold toilet seat — controlled and deliberate. Pause for a beat with your weight fully on the box, then explode up like the box is on fire. This teaches you to generate power from a dead stop.',
  'smith machine squat': 'Walk your feet slightly forward of the bar so you can sit back more naturally. Lower to parallel and think about spreading the floor apart with your feet. Press up and squeeze your quads hard at the top.',
  'belt squat': 'This takes your spine completely out of the equation, so go deep and heavy. Spread the floor apart with your feet and sit between your hips. Drive up by pushing the platforms away — your back stays happy while your legs get destroyed.',
  'pistol squat': 'Sit back on one leg like you\'re lowering into a tiny invisible chair. Extend your other leg forward and keep your arms out for balance. If you can\'t go full depth yet, squat to a low bench and work your way down over time.',
  'jefferson squat': 'Straddle the bar with one foot forward and one back, like a lunge stance. Grip the bar and drop your hips straight down, keeping your torso upright. This feels weird at first but it lights up your quads, glutes, and adductors all at once.',
  'zercher squat': 'Cradle the bar in your elbow crooks like you\'re carrying a sleeping child. Squat deep and use the bar position to keep your torso upright naturally. Your core and upper back will work overtime — that\'s a feature, not a bug.',
  // Legs — Hamstrings
  'leg curl': 'Dig your hips into the pad so they don\'t lift when it gets hard — that\'s the most common cheat. Curl your heels toward your butt and squeeze your hamstrings like you\'re trying to crack a walnut behind your knee. Lower slow; if the weight stack clangs, you\'re going too fast.',
  'seated leg curl': 'Sit tall and curl your heels under the seat as far as they\'ll go. Squeeze your hamstrings hard at the bottom like you\'re digging your heels into sand. Return slowly and resist the pad pulling your legs straight — that eccentric is gold.',
  'stiff leg deadlift': 'Keep your legs almost straight — a tiny bend in the knees is fine but no more. Push your hips back and lower the bar until your hamstrings scream for mercy. Your back stays flat as a table the entire time.',
  'romanian deadlift (dumbbell)': 'Push your hips back like you\'re bumping a door closed behind you. Keep the dumbbells grazing your thighs the entire way down. When you feel your hamstrings hit their limit, that\'s your bottom — drive your hips forward to stand.',
  'single leg romanian deadlift': 'Think about reaching your back leg and the weight in opposite directions like a seesaw. Your planted leg has a tiny knee bend that doesn\'t change. If you\'re wobbling everywhere, touch a wall for balance — wobbling means your hamstrings aren\'t working.',
  'nordic hamstring curl': 'Anchor your ankles and lower yourself forward as slowly as humanly possible. Fight gravity with everything your hamstrings have — you should be shaking. Catch yourself at the bottom and push back up with your hands if needed.',
  'glute ham raise': 'Start by hinging at the hips, then curl your body up using only your hamstrings — no hip extension. Imagine your feet are pulling the pad toward your butt. This is one of the hardest hamstring exercises in existence, so partial reps still count.',
  'cable pull-through': 'Face away from the cable with the rope between your legs and take a big step forward. Hinge at the hips, pushing your butt toward the cable like you\'re mooning someone behind you. Snap your hips forward and stand tall, squeezing your glutes at the top.',
  // Legs — Glutes
  'hip thrust': 'Shoulder blades on the bench, feet flat, and drive your hips to the ceiling. Squeeze your glutes at the top like you\'re pinching a coin between your cheeks. If you feel this in your lower back, tuck your chin and think about curling your tailbone under.',
  'barbell hip thrust': 'Use a pad on the bar — this should hurt your glutes, not your hip bones. Plant your feet so your shins are vertical at the top. Drive up and hold the squeeze at the top for a full second; half the benefit is in that lockout.',
  'glute bridge': 'Press your heels into the floor and drive your hips up like someone tied a rope to your belt. Squeeze your glutes so hard at the top that your hamstrings almost cramp. Lower just until your butt taps the floor — don\'t rest between reps.',
  'single leg glute bridge': 'One foot planted, the other leg pointed straight at the ceiling. Drive your hips up until your body makes a straight line from knee to shoulder. If one side is noticeably weaker, do extra reps on that side until it catches up.',
  'cable kickback': 'Hinge slightly at the hips and kick your leg straight back — not up. Think about stamping your footprint on the wall behind you. If you feel this in your lower back, you\'re kicking too high.',
  'donkey kick': 'Keep your knee bent at 90 degrees and push your foot toward the ceiling like you\'re stamping it. Squeeze your glute at the top and hold for a beat. Don\'t arch your lower back — your core stays tight like a plank.',
  'fire hydrant': 'On all fours, lift your knee out to the side like a dog at a hydrant — hence the name. Keep your hips square to the floor and don\'t lean away from the working leg. You should feel a deep burn on the side of your butt.',
  'sumo squat': 'Take a wide stance with toes pointed outward and drop your hips straight down between your feet. Push your knees out over your pinky toes as you lower. Drive up by squeezing your inner thighs and glutes together.',
  'frog pump': 'Lie on your back with the soles of your feet pressed together, knees splayed wide. Thrust your hips up and squeeze your glutes hard at the top. The frog leg position forces your glutes to do all the work — you\'ll feel it immediately.',
  // Legs — Calves
  'calf raise': 'Lower your heels as far below the step as possible — this deep stretch is where calves grow. Rise up on your toes as high as you can, like you\'re trying to peek over a tall fence. Hold the top for a two-count; quick bouncy reps do nothing for calves.',
  'seated calf raise': 'This targets your soleus, the flat muscle under your gastrocnemius. Lower your heels into a deep stretch and then press through your big toes. Calves are stubborn — do 15 or more reps and go until it burns unbearably.',
  'single leg calf raise': 'All your weight on one foot, lower into a deep stretch and power up to full height. Hold the top for a second and feel every fiber working. This exposes the calf imbalance most people have — prepare for one side to be much weaker.',
  'donkey calf raise': 'Hinge forward at the hips with weight on your lower back and rise up on your toes. The bent-over position puts an incredible stretch on your calves at the bottom. This old-school exercise was Arnold\'s favorite for a reason.',
  'smith machine calf raise': 'Stand on a block or plate with just your toes, heels hanging off. Lower deep for a full stretch, then rise up as high as possible. The smith bar keeps you stable so you can focus purely on the contraction.',
  'leg press calf raise': 'Place just the balls of your feet at the bottom edge of the platform. Push through your toes and squeeze at full extension. Lower slowly and let your toes pull back for a stretch — don\'t bounce.',
  // Legs — Adductors / Abductors
  'adductor machine': 'Squeeze your legs together like you\'re trying to crush a watermelon between your thighs. Hold the squeeze at the closed position for a beat. Open slowly against the resistance — don\'t just let your legs fly apart.',
  'abductor machine': 'Push your knees apart like you\'re trying to rip your pants at the seams. Squeeze the outside of your hips at full range and hold. Bring them back together slowly; the machine shouldn\'t clank.',
  'cable hip adduction': 'Stand tall and sweep your working leg across your body like you\'re kicking a soccer ball sideways. Squeeze your inner thigh at the peak of the movement. Return slowly — the cable\'s resistance on the way back is half the exercise.',
  'cable hip abduction': 'Stand tall and push your leg out to the side against the cable. Think about leading with your heel and squeezing the side of your hip. Don\'t lean away — keep your torso vertical so your glute med does all the work.',
  'lateral band walk': 'Sit into a quarter squat and stay there the entire time — no popping up between steps. Step wide enough that the band is trying to snap your knees together. Keep your toes pointed forward; duck feet is cheating.',
  'copenhagen plank': 'Side plank position with your top foot on a bench and bottom foot hovering. Squeeze your inner thigh to hold yourself up — it\'s like a side plank powered by your adductors. If you can hold this for 30 seconds, your groin strength is solid.',
  // Core
  'plank': 'Squeeze your glutes and brace your abs like someone\'s about to drop a medicine ball on your stomach. Push the floor away through your forearms so your upper back isn\'t sagging. If your hips drop or pike up, the set is over — quality reps only.',
  'side plank': 'Stack your feet and drive your bottom hip toward the ceiling. Your body should be a straight steel beam from ankle to ear. If your hip sags, prop your top foot in front of your bottom foot for extra stability.',
  'crunch': 'Think about bringing your ribcage toward your pelvis, not your head toward your knees. Keep a fist-sized gap between your chin and chest the entire time. If your neck hurts, you\'re pulling with your hands — press your tongue to the roof of your mouth instead.',
  'reverse crunch': 'Curl your tailbone off the floor by driving your knees toward your chin, not just your chest. Your hips should physically lift off the ground — if they don\'t, you\'re just doing a knee tuck. Lower your feet back slowly; don\'t let them drop.',
  'russian twist': 'Lean back until you feel your abs catch fire and hold that angle. Rotate from your ribcage, not your arms — your belly button should turn with each twist. Touch the weight to the floor on each side for full range.',
  'hanging leg raise': 'Dead hang with your arms straight, then curl your pelvis up by imagining you\'re showing someone the bottom of your shoes. Don\'t just swing your legs — if you\'re using momentum, you\'re doing hanging leg swings, not raises. Lower slowly and stop any swaying before the next rep.',
  'hanging knee raise': 'Hang still, then curl your knees toward your chest by rolling your pelvis under you. Squeeze your abs at the top like you\'re crunching into a ball. Lower slowly — if you\'re swinging like a pendulum, reset before each rep.',
  'cable crunch': 'Kneel down and lock the rope at your forehead — your hands don\'t move from here. Crunch by curling your ribcage toward your hips, not by bowing at the waist. If your hips are moving, you\'re doing it wrong — only your spine flexes.',
  'mountain climber': 'Get into a push-up position and drive each knee toward the opposite elbow like you\'re sprinting on the floor. Your hips stay level — don\'t let your butt bounce up and down. The faster you go, the more cardio; the slower, the more core.',
  'bicycle crunch': 'Bring your shoulder to the opposite knee, not just your elbow — rotate your whole torso. Extend the other leg straight and low like you\'re pushing a pedal away. Slow reps build more muscle; fast reps just give you a sore neck.',
  'dead bug': 'Press your lower back into the floor so hard you could crush a grape under your spine. Extend one arm and the opposite leg while keeping that back completely glued down. If your back arches off the floor, you went too far — that\'s your range of motion limit today.',
  'bird dog': 'Reach your arm forward and opposite leg back like they\'re being pulled by ropes in opposite directions. Keep your hips level — tape a glass of water to your lower back and don\'t spill it. Hold for a two-count at full extension before switching.',
  'ab wheel rollout': 'Roll out only as far as you can without your lower back caving in like a hammock. Tuck your tailbone under and think about pulling your belt buckle to your chin on the way back. If you can\'t do these from the floor, start from your knees.',
  'pallof press': 'Stand sideways to the cable and press the handle straight out from your chest. The cable is trying to twist you — your job is to resist it and stay square. Hold at full extension for a two-count; that\'s where the magic happens.',
  'woodchop': 'It\'s a rotation, not a chop — your arms stay straight and your torso does the twisting. Pivot through your hips and feel your obliques wringing out like a towel. Control the return; letting the cable yank you back is a recipe for a tweaked back.',
  'reverse woodchop': 'Start low and rotate diagonally upward, pivoting through your hips and core. Think about scooping something off the floor and putting it on a high shelf. Your arms are just along for the ride — the power comes from your obliques.',
  'v-up': 'Reach your hands toward your toes as your legs and torso fold together like a jackknife. Your body should make a V shape at the top, balanced on your tailbone. If you can\'t keep your legs straight, bend your knees slightly until you build the strength.',
  'toe touch': 'Legs straight up at 90 degrees, reach your hands toward your toes by crunching your shoulders off the floor. Think about lifting your shoulder blades, not just reaching with your arms. Lower your shoulders back slowly — your legs stay perfectly vertical.',
  'flutter kick': 'Press your lower back into the floor and keep it glued there the entire time. Kick with small, controlled scissors — about 6 inches of movement. The moment your lower back pops off the floor, your set is done.',
  'leg raise': 'Press your hands under your butt for support and keep your lower back welded to the floor. Raise your legs to 90 degrees with control, then lower them as slowly as possible. Stop lowering when you feel your back start to arch — that\'s your current range.',
  'sit-up': 'Hook your feet and curl up by rolling through your spine one vertebra at a time. Don\'t yank yourself up with your hip flexors — if you feel this in your hip crease, slow way down. Lower with the same rolling motion, controlling every inch.',
  'dragon flag': 'Grip the bench behind your head and lift your entire body as one rigid unit. Lower slowly like a drawbridge being lowered — only your shoulder blades stay on the bench. If you can\'t keep your body straight, bend your knees to reduce the lever.',
  'ab crunch machine': 'Resist the urge to go heavy — this is about squeezing, not smashing. Curl your ribcage toward your pelvis and hold the contraction for a beat. Return slowly and don\'t let the weight stack touch between reps.',
  'decline sit-up': 'The steeper the angle, the harder it is — start moderate and earn the steep decline. Curl up by rolling through your spine, not jackknifing at your hips. Cross your arms over your chest or hold a plate for added challenge.',
  'hollow body hold': 'Press your lower back into the floor and lift your shoulders and legs until your body makes a banana shape. Squeeze everything — your abs, your quads, your glutes — like you\'re bracing for impact. If your lower back lifts off the floor, raise your legs higher until you\'re strong enough.',
  'l-sit': 'Support yourself on parallettes or dip bars and lift your straight legs to horizontal. Push the floor away hard and keep your shoulders packed down away from your ears. Even 5-second holds will build serious core strength if you\'re fully locked out.',
  'windshield wiper': 'Hang from a bar with legs at 90 degrees and rotate them side to side like a metronome. Your obliques have to work overtime to control this swinging motion. Start with a small range and earn the full wiper arc as your strength grows.',
  'suitcase carry': 'Grab a heavy dumbbell in one hand and walk without letting your torso lean to that side. Imagine a string is pulling you straight up from the top of your head. Your obliques are working to keep you upright — that\'s an asymmetric carry at its finest.',
  // Cardio
  'incline treadmill walk': 'Crank the incline to 10-15% and walk at a pace that makes conversation tough but possible. Keep your hands off the rails — holding on cuts the workload in half. Stand tall and drive through your heels; you\'ll feel your glutes and hamstrings working.',
  'brisk walk': 'Walk fast enough that you can talk but can\'t sing — that\'s the right zone. Pump your arms naturally and take slightly longer strides than usual. This is the most underrated fat-burning exercise; consistency beats intensity here.',
  'jump rope': 'Stay on the balls of your feet and jump just an inch off the ground — less is more. Keep your elbows pinned to your sides and spin the rope with your wrists, not your shoulders. If you trip, reset immediately; standing around is the only wasted time.',
  'rowing machine': 'It\'s legs, back, arms on the pull — then arms, back, legs on the return. Think about pushing the footplate away, not pulling the handle. Keep your chain height level and your strokes smooth; jerky rowing wastes energy.',
  'stair climber': 'Stand tall and drive through each step — don\'t lean on the rails like a crutch. Take full steps and push through your heel to light up your glutes. If you\'re death-gripping the handles, lower the speed until you can stand freely.',
  'battle ropes': 'Sit into a shallow squat and create waves by slamming alternating arms like you\'re angry at the floor. Keep your core braced and your shoulders packed — don\'t shrug up to your ears. Big waves from the shoulders, not little flicks from the wrists.',
  'box jump': 'Swing your arms and explode upward, landing quietly on the box like a cat. Stand up fully on top before stepping back down — don\'t jump down; that\'s how Achilles tendons get angry. If you\'re hesitating before jumping, lower the box.',
  'burpee': 'Drop to the floor fast, peel yourself up with a push-up, and jump like the floor is lava. The whole point is to keep moving — standing around between reps defeats the purpose. Land softly on the jump and immediately drop into the next rep.',
  'jumping jack': 'Snap your arms fully overhead and your feet wider than shoulder-width on every single rep. Land softly on the balls of your feet, not flat-footed like a concrete slab. Keep a rhythm going — this should feel like a metronome, not a random flail.',
  'high knees': 'Drive your knees up until your thighs are parallel to the floor every rep. Pump your arms hard — they set the pace for your legs. Stay on the balls of your feet and think about running in place through wet concrete.',
  'kettlebell swing': 'It\'s a hip hinge, not a squat — your power comes from snapping your hips, not lifting with your arms. Hike the bell back between your legs like a football snap, then stand up violently. The bell should float to chest height on momentum alone.',
  'assault bike': 'Push and pull the handles while driving your legs — your whole body should be working. The harder you go, the more resistance it creates, so pace yourself or it\'ll humble you fast. Keep your core tight and don\'t let your torso collapse forward.',
  'sprints': 'Drive your knees high and pump your arms like pistons — your arms set the speed for your legs. Lean slightly forward at the start and stay on the balls of your feet the entire sprint. Full recovery between sets; sprints done tired are just slow jogging.',
  'sled push': 'Get low and lean into the sled at a 45-degree angle, arms locked out. Drive each leg forward like you\'re stomping through mud. Keep your head down and your hips low — if you stand up tall, you lose all your leverage.',
  'sled pull': 'Sit back and pull the rope hand over hand, using your whole back and biceps. Dig your heels in and lean away from the sled. Keep your pulls long and rhythmic — short choppy pulls waste energy.',
  'bear crawl': 'Keep your knees hovering just an inch off the floor — that\'s what makes this brutal. Move opposite hand and foot together, keeping your hips level and your back flat. If your butt is up in the air, lower your hips until your back is a tabletop.',
  'elliptical': 'Push and pull the handles to involve your upper body — don\'t just let your legs do everything. Keep your feet flat on the pedals and your posture tall. Increase resistance for a workout; zero resistance is just leg swinging.',
  'cycling': 'Set your seat height so your knee has a slight bend at the bottom of the pedal stroke. Pedal in smooth circles, pulling up as well as pushing down. Keep your upper body relaxed and quiet — bouncing in the saddle means the resistance is too high.',
  'swimming': 'Reach long on every stroke and rotate your body like a log rolling through the water. Exhale steadily underwater and turn your head to breathe, don\'t lift it. Smooth, patient strokes beat thrashing — the fastest swimmers look the calmest.',
  // Bands
  'band row': 'Anchor the band at chest height and step back until there\'s tension even with arms outstretched. Pull your elbows past your ribcage like you\'re trying to start two lawnmowers at once. Squeeze your shoulder blades together and hold for a beat before returning.',
  'band squat': 'Stand on the band and hold the handles at your shoulders — the tension increases as you stand up. Sit deep like a normal squat and explode upward against the growing resistance. The band teaches you to accelerate through the whole rep, not just the bottom.',
  'band chest press': 'Wrap the band behind your back and press forward like you\'re shoving a heavy door open. The resistance builds as you extend — squeeze hard at full lockout. Return slowly; letting the band snap your arms back is wasted potential.',
  'band bicep curl': 'Stand on the band and curl with your palms up, keeping your elbows glued to your sides. The tension ramps up as you curl higher, so the squeeze at the top is where the magic lives. Lower with control; the band wants to snap back but don\'t let it.',
  'band tricep extension': 'Anchor overhead and grip the band behind your head. Extend your arms down by straightening at the elbow only. Fight the band on the way back up — it\'s trying to accelerate your arm and you should resist.',
  'band face pull': 'Anchor at face height and pull the band apart toward your face, finishing with your hands wide. Squeeze your rear delts and hold the spread position for a full second. This is prehab gold — light tension and high reps keep your shoulders healthy.',
  'band lateral raise': 'Stand on the band and raise your arms to shoulder height, leading with your elbows. The band gets harder at the top, which is exactly where your delts need to work hardest. Lower with control and don\'t let the band pull your arms down faster than you want.',
  'band good morning': 'Loop the band around your neck and under your feet, then hinge at the hips with a flat back. Push your butt back until your hamstrings are loaded, then snap your hips forward to stand. The band adds resistance at the top where the movement is usually easiest.',
  'band hip thrust': 'Band across your hips, shoulders on a bench, and drive up against the resistance. The band pulls hardest at the top, forcing a maximal glute squeeze at lockout. Hold the top for a two-count — that\'s where bands really shine for this exercise.',
  'band leg curl': 'Anchor the band low and loop it around your ankle. Curl your heel toward your butt against the resistance. The band teaches your hamstrings to contract fast — use it as a warm-up or finisher.',
  'band deadlift': 'Stand on the band and grip it at hip height. Stand up by extending your hips and knees, fighting increasing resistance the taller you get. This teaches you to drive hard through lockout, which carries over to barbell deadlifts.',
  // Full body / Compound
  'clean and press': 'Rip the bar from the floor to your shoulders in one aggressive pull, catching it on your front delts. Without pausing, press it overhead by dipping your knees and driving through. This should feel like one continuous wave of effort from floor to ceiling.',
  'thruster': 'Drop into a front squat, then stand up so explosively that the barbell practically floats overhead. The squat and press should be one seamless motion — any pause between them wastes momentum. If you\'re doing these right, your lungs will give out before your muscles.',
  'man maker': 'Push-up, row left, row right, clean to shoulders, press overhead — that\'s one rep. Keep your hips level during the rows; they want to twist. This is meant to be miserable; embrace the suffering and keep moving.',
  'turkish get-up': 'Keep your eyes locked on the weight overhead the entire time like it might fall on you — because it might. Move slowly through each position: roll, post, sweep, lunge, stand. If you rush this, you\'ll either drop the weight or miss the whole point of the exercise.',
  'power clean': 'Start with the bar over your mid-foot and explode upward by triple-extending ankles, knees, and hips. Whip your elbows around and catch the bar on your front delts in a quarter squat. The pull should feel like you\'re jumping while holding the bar.',
  'snatch': 'Rip the bar from the floor to overhead in one explosive motion — think about throwing the bar at the ceiling. Drop under it fast and catch it with locked arms in a deep squat. This is the most technical lift in the gym; start light and earn every pound.',
  'hang clean': 'Start at your hips, dip slightly, then explode upward by snapping your hips like you\'re jumping. Whip your elbows around fast and catch the bar on your shoulders. The dip-and-drive is everything — without that hip snap, you\'re just muscling the bar up.',
  'push press': 'Dip your knees a few inches and then drive the bar off your shoulders with your leg power. Your legs start the press, your arms finish it — that\'s what makes it different from a strict press. Lock out hard overhead and control the bar back to your shoulders.',
  'clean': 'Pull the bar from the floor using your legs and hips, not your arms — your arms are just ropes. Catch the bar on your front delts by whipping your elbows around lightning fast. Stand up tall from the catch position with your chest proud.',
  'muscle-up': 'Pull hard enough to get your chest over the bar, not just your chin. At the transition, lean forward aggressively and push your hands down to get on top. If you can\'t do one yet, work explosive pull-ups and deep dips separately.',
  'wall ball': 'Squat deep with the ball at your chest, then stand up so explosively that the ball launches itself to the target. Catch it softly and immediately sink into the next squat — no pausing at the top. Your legs do the throwing; your arms just guide the ball.',
};

export function getInstructions(name: string): string {
  const lower = name.toLowerCase();
  if (EXERCISE_INSTRUCTIONS[lower]) return EXERCISE_INSTRUCTIONS[lower];
  for (const [key, instructions] of Object.entries(EXERCISE_INSTRUCTIONS)) {
    if (lower.includes(key) || key.includes(lower)) return instructions;
  }
  // Generic fallbacks by keyword
  if (lower.includes('bench') || lower.includes('chest') || lower.includes('fly') || lower.includes('push'))
    return 'Pin your shoulder blades together like you\'re cracking a walnut between them. Lower the weight like you\'re pulling a loaded spring, then press up explosively. If your shoulders creep forward, reset your setup.';
  if (lower.includes('row') || lower.includes('pull') || lower.includes('lat') || lower.includes('back'))
    return 'Lead with your elbows, not your hands — your arms are just hooks attached to your back. Squeeze your shoulder blades together at the top like you\'re pinching a pencil between them. Lower slowly and feel the stretch.';
  if (lower.includes('squat') || lower.includes('leg') || lower.includes('lunge'))
    return 'Screw your feet into the floor and spread the ground apart. Sit back like there\'s a chair behind you, keeping your chest proud. Drive up by pushing the earth away from you.';
  if (lower.includes('press') || lower.includes('shoulder') || lower.includes('raise'))
    return 'Stack your wrists over your elbows like pillars supporting a roof. Press up and lock out with confidence, then lower like you\'re compressing a spring. If your back arches, brace harder or go lighter.';
  if (lower.includes('curl') || lower.includes('bicep') || lower.includes('tricep'))
    return 'Glue your elbows to your sides — they don\'t move the entire set. Squeeze at the top like you\'re flexing for a photo and lower for a slow three-count. If you\'re swinging, the weight is too heavy for you right now.';
  if (lower.includes('plank') || lower.includes('crunch') || lower.includes('ab') || lower.includes('core'))
    return 'Brace your core like someone\'s about to drop a medicine ball on your stomach. Move your ribcage toward your pelvis, not your head toward your knees. The moment your form breaks, the set is over.';
  if (lower.includes('calf') || lower.includes('raise'))
    return 'Lower into a deep stretch like you\'re trying to touch your heels to the floor. Rise up as high as possible and hold the squeeze for a two-count. Calves are stubborn — slow reps and full range are the only things that work.';
  return 'Own every inch of every rep — control the weight, don\'t let it control you. Breathe out on the effort and brace your core like you\'re about to take a punch. If your form breaks, the set is done.';
}

// Categorized exercise database for the quick workout picker
export interface ExerciseEntry {
  name: string;
  category: string;
}

export const EXERCISE_CATEGORIES = ['Chest', 'Back', 'Shoulders', 'Arms', 'Legs', 'Core', 'Cardio', 'Bands', 'Full Body'] as const;

export const EXERCISE_DATABASE: ExerciseEntry[] = [
  // === CHEST (19) ===
  { name: 'Barbell Bench Press', category: 'Chest' },
  { name: 'Dumbbell Bench Press', category: 'Chest' },
  { name: 'Incline Bench Press', category: 'Chest' },
  { name: 'Dumbbell Incline Press', category: 'Chest' },
  { name: 'Decline Bench Press', category: 'Chest' },
  { name: 'Dumbbell Decline Press', category: 'Chest' },
  { name: 'Chest Fly', category: 'Chest' },
  { name: 'Incline Dumbbell Fly', category: 'Chest' },
  { name: 'Push-Up', category: 'Chest' },
  { name: 'Wide Push-Up', category: 'Chest' },
  { name: 'Diamond Push-Up', category: 'Chest' },
  { name: 'Decline Push-Up', category: 'Chest' },
  { name: 'Cable Crossover', category: 'Chest' },
  { name: 'Low Cable Fly', category: 'Chest' },
  { name: 'Machine Chest Press', category: 'Chest' },
  { name: 'Pec Deck', category: 'Chest' },
  { name: 'Svend Press', category: 'Chest' },
  { name: 'Dumbbell Pullover', category: 'Chest' },
  { name: 'Floor Press', category: 'Chest' },

  // === BACK (22) ===
  { name: 'Pull-Up', category: 'Back' },
  { name: 'Chin-Up', category: 'Back' },
  { name: 'Lat Pulldown', category: 'Back' },
  { name: 'Close Grip Lat Pulldown', category: 'Back' },
  { name: 'Barbell Row', category: 'Back' },
  { name: 'Dumbbell Row', category: 'Back' },
  { name: 'Seated Cable Row', category: 'Back' },
  { name: 'Deadlift', category: 'Back' },
  { name: 'Sumo Deadlift', category: 'Back' },
  { name: 'Romanian Deadlift', category: 'Back' },
  { name: 'T-Bar Row', category: 'Back' },
  { name: 'Pendlay Row', category: 'Back' },
  { name: 'Meadows Row', category: 'Back' },
  { name: 'Inverted Row', category: 'Back' },
  { name: 'Cable Pullover', category: 'Back' },
  { name: 'Straight Arm Pulldown', category: 'Back' },
  { name: 'Machine Row', category: 'Back' },
  { name: 'Chest Supported Row', category: 'Back' },
  { name: 'Single Arm Cable Row', category: 'Back' },
  { name: 'Rack Pull', category: 'Back' },
  { name: 'Good Morning', category: 'Back' },
  { name: 'Back Extension', category: 'Back' },
  { name: 'Seal Row', category: 'Back' },
  { name: 'Landmine Row', category: 'Back' },

  // === SHOULDERS (20) ===
  { name: 'Overhead Press', category: 'Shoulders' },
  { name: 'Dumbbell Shoulder Press', category: 'Shoulders' },
  { name: 'Lateral Raise', category: 'Shoulders' },
  { name: 'Cable Lateral Raise', category: 'Shoulders' },
  { name: 'Front Raise', category: 'Shoulders' },
  { name: 'Cable Front Raise', category: 'Shoulders' },
  { name: 'Face Pull', category: 'Shoulders' },
  { name: 'Rear Delt Fly', category: 'Shoulders' },
  { name: 'Arnold Press', category: 'Shoulders' },
  { name: 'Machine Shoulder Press', category: 'Shoulders' },
  { name: 'Barbell Upright Row', category: 'Shoulders' },
  { name: 'Dumbbell Upright Row', category: 'Shoulders' },
  { name: 'Reverse Pec Deck', category: 'Shoulders' },
  { name: 'Landmine Press', category: 'Shoulders' },
  { name: 'Dumbbell Shrug', category: 'Shoulders' },
  { name: 'Barbell Shrug', category: 'Shoulders' },
  { name: 'Behind the Neck Press', category: 'Shoulders' },
  { name: 'Cable Rear Delt Fly', category: 'Shoulders' },
  { name: 'Plate Front Raise', category: 'Shoulders' },
  { name: 'Lu Raise', category: 'Shoulders' },

  // === ARMS (28) ===
  // Biceps
  { name: 'Barbell Curl', category: 'Arms' },
  { name: 'Dumbbell Curl', category: 'Arms' },
  { name: 'Hammer Curl', category: 'Arms' },
  { name: 'Preacher Curl', category: 'Arms' },
  { name: 'Concentration Curl', category: 'Arms' },
  { name: 'Incline Dumbbell Curl', category: 'Arms' },
  { name: 'Cable Curl', category: 'Arms' },
  { name: 'Spider Curl', category: 'Arms' },
  { name: 'EZ Bar Curl', category: 'Arms' },
  { name: 'Reverse Curl', category: 'Arms' },
  { name: 'Bayesian Curl', category: 'Arms' },
  { name: 'Cable Hammer Curl', category: 'Arms' },
  { name: 'Zottman Curl', category: 'Arms' },
  { name: '21s Bicep Curl', category: 'Arms' },
  // Triceps
  { name: 'Tricep Pushdown', category: 'Arms' },
  { name: 'Skull Crusher', category: 'Arms' },
  { name: 'Tricep Dip', category: 'Arms' },
  { name: 'Close Grip Bench Press', category: 'Arms' },
  { name: 'Overhead Tricep Extension', category: 'Arms' },
  { name: 'Cable Overhead Extension', category: 'Arms' },
  { name: 'Tricep Kickback', category: 'Arms' },
  { name: 'Rope Pushdown', category: 'Arms' },
  { name: 'Single Arm Pushdown', category: 'Arms' },
  { name: 'Dip Machine', category: 'Arms' },
  { name: 'Bench Dip', category: 'Arms' },
  { name: 'JM Press', category: 'Arms' },
  // Forearms
  { name: 'Wrist Curl', category: 'Arms' },
  { name: 'Reverse Wrist Curl', category: 'Arms' },
  { name: 'Farmer Carry', category: 'Arms' },

  // === LEGS (48) ===
  // Quads
  { name: 'Squat', category: 'Legs' },
  { name: 'Barbell Squat', category: 'Legs' },
  { name: 'Front Squat', category: 'Legs' },
  { name: 'Leg Press', category: 'Legs' },
  { name: 'Hack Squat', category: 'Legs' },
  { name: 'Lunge', category: 'Legs' },
  { name: 'Walking Lunge', category: 'Legs' },
  { name: 'Reverse Lunge', category: 'Legs' },
  { name: 'Bulgarian Split Squat', category: 'Legs' },
  { name: 'Leg Extension', category: 'Legs' },
  { name: 'Goblet Squat', category: 'Legs' },
  { name: 'Step-Up', category: 'Legs' },
  { name: 'Wall Sit', category: 'Legs' },
  { name: 'Sissy Squat', category: 'Legs' },
  { name: 'Single Leg Press', category: 'Legs' },
  { name: 'Box Squat', category: 'Legs' },
  { name: 'Smith Machine Squat', category: 'Legs' },
  { name: 'Belt Squat', category: 'Legs' },
  { name: 'Pistol Squat', category: 'Legs' },
  { name: 'Jefferson Squat', category: 'Legs' },
  { name: 'Zercher Squat', category: 'Legs' },
  // Hamstrings
  { name: 'Leg Curl', category: 'Legs' },
  { name: 'Seated Leg Curl', category: 'Legs' },
  { name: 'Stiff Leg Deadlift', category: 'Legs' },
  { name: 'Romanian Deadlift (Dumbbell)', category: 'Legs' },
  { name: 'Single Leg Romanian Deadlift', category: 'Legs' },
  { name: 'Nordic Hamstring Curl', category: 'Legs' },
  { name: 'Glute Ham Raise', category: 'Legs' },
  { name: 'Cable Pull-Through', category: 'Legs' },
  // Glutes
  { name: 'Hip Thrust', category: 'Legs' },
  { name: 'Barbell Hip Thrust', category: 'Legs' },
  { name: 'Glute Bridge', category: 'Legs' },
  { name: 'Single Leg Glute Bridge', category: 'Legs' },
  { name: 'Cable Kickback', category: 'Legs' },
  { name: 'Donkey Kick', category: 'Legs' },
  { name: 'Fire Hydrant', category: 'Legs' },
  { name: 'Sumo Squat', category: 'Legs' },
  { name: 'Frog Pump', category: 'Legs' },
  // Calves
  { name: 'Calf Raise', category: 'Legs' },
  { name: 'Seated Calf Raise', category: 'Legs' },
  { name: 'Single Leg Calf Raise', category: 'Legs' },
  { name: 'Donkey Calf Raise', category: 'Legs' },
  { name: 'Smith Machine Calf Raise', category: 'Legs' },
  { name: 'Leg Press Calf Raise', category: 'Legs' },
  // Adductors/Abductors
  { name: 'Adductor Machine', category: 'Legs' },
  { name: 'Abductor Machine', category: 'Legs' },
  { name: 'Cable Hip Adduction', category: 'Legs' },
  { name: 'Cable Hip Abduction', category: 'Legs' },
  { name: 'Lateral Band Walk', category: 'Legs' },
  { name: 'Copenhagen Plank', category: 'Legs' },

  // === CORE (28) ===
  { name: 'Plank', category: 'Core' },
  { name: 'Side Plank', category: 'Core' },
  { name: 'Crunch', category: 'Core' },
  { name: 'Reverse Crunch', category: 'Core' },
  { name: 'Russian Twist', category: 'Core' },
  { name: 'Hanging Leg Raise', category: 'Core' },
  { name: 'Hanging Knee Raise', category: 'Core' },
  { name: 'Cable Crunch', category: 'Core' },
  { name: 'Mountain Climber', category: 'Core' },
  { name: 'Bicycle Crunch', category: 'Core' },
  { name: 'Dead Bug', category: 'Core' },
  { name: 'Bird Dog', category: 'Core' },
  { name: 'Ab Wheel Rollout', category: 'Core' },
  { name: 'Pallof Press', category: 'Core' },
  { name: 'Woodchop', category: 'Core' },
  { name: 'Reverse Woodchop', category: 'Core' },
  { name: 'V-Up', category: 'Core' },
  { name: 'Toe Touch', category: 'Core' },
  { name: 'Flutter Kick', category: 'Core' },
  { name: 'Leg Raise', category: 'Core' },
  { name: 'Sit-Up', category: 'Core' },
  { name: 'Dragon Flag', category: 'Core' },
  { name: 'Ab Crunch Machine', category: 'Core' },
  { name: 'Decline Sit-Up', category: 'Core' },
  { name: 'Hollow Body Hold', category: 'Core' },
  { name: 'L-Sit', category: 'Core' },
  { name: 'Windshield Wiper', category: 'Core' },
  { name: 'Suitcase Carry', category: 'Core' },

  // === CARDIO (19) ===
  { name: 'Incline Treadmill Walk', category: 'Cardio' },
  { name: 'Brisk Walk', category: 'Cardio' },
  { name: 'Jump Rope', category: 'Cardio' },
  { name: 'Rowing Machine', category: 'Cardio' },
  { name: 'Stair Climber', category: 'Cardio' },
  { name: 'Battle Ropes', category: 'Cardio' },
  { name: 'Box Jump', category: 'Cardio' },
  { name: 'Burpee', category: 'Cardio' },
  { name: 'Jumping Jack', category: 'Cardio' },
  { name: 'High Knees', category: 'Cardio' },
  { name: 'Kettlebell Swing', category: 'Cardio' },
  { name: 'Assault Bike', category: 'Cardio' },
  { name: 'Sprints', category: 'Cardio' },
  { name: 'Sled Push', category: 'Cardio' },
  { name: 'Sled Pull', category: 'Cardio' },
  { name: 'Bear Crawl', category: 'Cardio' },
  { name: 'Elliptical', category: 'Cardio' },
  { name: 'Cycling', category: 'Cardio' },
  { name: 'Swimming', category: 'Cardio' },

  // === BANDS (12) ===
  { name: 'Band Pull-Apart', category: 'Bands' },
  { name: 'Band Row', category: 'Bands' },
  { name: 'Band Squat', category: 'Bands' },
  { name: 'Band Chest Press', category: 'Bands' },
  { name: 'Band Bicep Curl', category: 'Bands' },
  { name: 'Band Tricep Extension', category: 'Bands' },
  { name: 'Band Face Pull', category: 'Bands' },
  { name: 'Band Lateral Raise', category: 'Bands' },
  { name: 'Band Good Morning', category: 'Bands' },
  { name: 'Band Hip Thrust', category: 'Bands' },
  { name: 'Band Leg Curl', category: 'Bands' },
  { name: 'Band Deadlift', category: 'Bands' },

  // === FULL BODY (11) ===
  { name: 'Clean and Press', category: 'Full Body' },
  { name: 'Thruster', category: 'Full Body' },
  { name: 'Man Maker', category: 'Full Body' },
  { name: 'Turkish Get-Up', category: 'Full Body' },
  { name: 'Power Clean', category: 'Full Body' },
  { name: 'Snatch', category: 'Full Body' },
  { name: 'Hang Clean', category: 'Full Body' },
  { name: 'Push Press', category: 'Full Body' },
  { name: 'Clean', category: 'Full Body' },
  { name: 'Muscle-Up', category: 'Full Body' },
  { name: 'Wall Ball', category: 'Full Body' },

  // === ADDITIONAL CHEST (10) ===
  { name: 'Smith Machine Bench Press', category: 'Chest' },
  { name: 'Smith Machine Incline Press', category: 'Chest' },
  { name: 'Plate Squeeze Press', category: 'Chest' },
  { name: 'Chest Dip', category: 'Chest' },
  { name: 'Cable Chest Press', category: 'Chest' },
  { name: 'Incline Cable Fly', category: 'Chest' },
  { name: 'Hex Press', category: 'Chest' },
  { name: 'Close Grip Push-Up', category: 'Chest' },
  { name: 'Archer Push-Up', category: 'Chest' },
  { name: 'Explosive Push-Up', category: 'Chest' },

  // === ADDITIONAL BACK (10) ===
  { name: 'Wide Grip Pull-Up', category: 'Back' },
  { name: 'Neutral Grip Pull-Up', category: 'Back' },
  { name: 'Kneeling Cable Pulldown', category: 'Back' },
  { name: 'Behind Neck Lat Pulldown', category: 'Back' },
  { name: 'Dumbbell Pullover', category: 'Back' },
  { name: 'Yates Row', category: 'Back' },
  { name: 'Smith Machine Row', category: 'Back' },
  { name: 'Single Arm Lat Pulldown', category: 'Back' },
  { name: 'Cable Face Pull', category: 'Back' },
  { name: 'Snatch Grip Deadlift', category: 'Back' },

  // === ADDITIONAL SHOULDERS (8) ===
  { name: 'Seated Dumbbell Lateral Raise', category: 'Shoulders' },
  { name: 'Machine Lateral Raise', category: 'Shoulders' },
  { name: 'Bent Over Lateral Raise', category: 'Shoulders' },
  { name: 'Bradford Press', category: 'Shoulders' },
  { name: 'Z Press', category: 'Shoulders' },
  { name: 'Viking Press', category: 'Shoulders' },
  { name: 'Dumbbell Y Raise', category: 'Shoulders' },
  { name: 'Kettlebell Press', category: 'Shoulders' },

  // === ADDITIONAL ARMS (12) ===
  { name: 'Cross Body Hammer Curl', category: 'Arms' },
  { name: 'Drag Curl', category: 'Arms' },
  { name: 'Machine Preacher Curl', category: 'Arms' },
  { name: 'Cable Preacher Curl', category: 'Arms' },
  { name: 'Waiter Curl', category: 'Arms' },
  { name: 'Lying Tricep Extension', category: 'Arms' },
  { name: 'French Press', category: 'Arms' },
  { name: 'Cable Tricep Kickback', category: 'Arms' },
  { name: 'Diamond Dip', category: 'Arms' },
  { name: 'Overhead Cable Curl', category: 'Arms' },
  { name: 'EZ Bar Preacher Curl', category: 'Arms' },
  { name: 'Incline Hammer Curl', category: 'Arms' },

  // === ADDITIONAL LEGS (20) ===
  { name: 'Narrow Stance Squat', category: 'Legs' },
  { name: 'Wide Stance Squat', category: 'Legs' },
  { name: 'Pause Squat', category: 'Legs' },
  { name: 'Safety Bar Squat', category: 'Legs' },
  { name: 'Curtsy Lunge', category: 'Legs' },
  { name: 'Deficit Lunge', category: 'Legs' },
  { name: 'Split Squat', category: 'Legs' },
  { name: 'Lateral Lunge', category: 'Legs' },
  { name: 'Pendulum Squat', category: 'Legs' },
  { name: 'V Squat', category: 'Legs' },
  { name: 'Narrow Stance Leg Press', category: 'Legs' },
  { name: 'Wide Stance Leg Press', category: 'Legs' },
  { name: 'Barbell Calf Raise', category: 'Legs' },
  { name: 'Dumbbell Lunge', category: 'Legs' },
  { name: 'Dumbbell Step-Up', category: 'Legs' },
  { name: 'Barbell Glute Bridge', category: 'Legs' },
  { name: 'Single Leg Leg Press', category: 'Legs' },
  { name: 'Leg Press (High Foot)', category: 'Legs' },
  { name: 'Leg Press (Low Foot)', category: 'Legs' },
  { name: 'Machine Hip Thrust', category: 'Legs' },

  // === ADDITIONAL CORE (12) ===
  { name: 'Weighted Plank', category: 'Core' },
  { name: 'Weighted Crunch', category: 'Core' },
  { name: 'Cable Pallof Press', category: 'Core' },
  { name: 'Landmine Rotation', category: 'Core' },
  { name: 'Farmer Walk', category: 'Core' },
  { name: 'Turkish Get-Up (Core)', category: 'Core' },
  { name: 'Stability Ball Crunch', category: 'Core' },
  { name: 'Medicine Ball Slam', category: 'Core' },
  { name: 'Plank Shoulder Tap', category: 'Core' },
  { name: 'Body Saw', category: 'Core' },
  { name: 'Stir the Pot', category: 'Core' },
  { name: 'Copenhagen Side Plank', category: 'Core' },

  // === ADDITIONAL CARDIO (10) ===
  { name: 'Skater Jump', category: 'Cardio' },
  { name: 'Tuck Jump', category: 'Cardio' },
  { name: 'Broad Jump', category: 'Cardio' },
  { name: 'Hill Sprint', category: 'Cardio' },
  { name: 'Prowler Push', category: 'Cardio' },
  { name: 'Ski Erg', category: 'Cardio' },
  { name: 'Versa Climber', category: 'Cardio' },
  { name: 'Jacob Ladder', category: 'Cardio' },
  { name: 'Shadow Boxing', category: 'Cardio' },
  { name: 'Jump Squat', category: 'Cardio' },

  // === ADDITIONAL FULL BODY (8) ===
  { name: 'Dumbbell Snatch', category: 'Full Body' },
  { name: 'Kettlebell Clean', category: 'Full Body' },
  { name: 'Kettlebell Snatch', category: 'Full Body' },
  { name: 'Devil Press', category: 'Full Body' },
  { name: 'Barbell Complex', category: 'Full Body' },
  { name: 'Bear Complex', category: 'Full Body' },
  { name: 'Hang Snatch', category: 'Full Body' },
  { name: 'Sumo Deadlift High Pull', category: 'Full Body' },
];
