/**
 * Auto-generated by scripts/map-exercise-models.js
 * Maps exercise names (lowercase) to GLB model assets.
 *
 * To regenerate: node scripts/map-exercise-models.js
 * To add models: drop .glb files in assets/models/ and rerun the script.
 */

const bicep_curl = require('../assets/models/bicep-curl.glb');

const MODEL_MAP: Record<string, any> = {
  'bicep curl': bicep_curl,
  '21s bicep curl': bicep_curl,
  'band bicep curl': bicep_curl,
};

/**
 * Returns the GLB model asset for a given exercise name, or null if no model exists.
 */
export function getExerciseModel(exerciseName: string): any | null {
  const key = exerciseName.toLowerCase().trim();
  // Exact match
  if (MODEL_MAP[key]) return MODEL_MAP[key];
  // Partial match — check if exercise name contains a mapped key
  for (const [mapKey, asset] of Object.entries(MODEL_MAP)) {
    if (key.includes(mapKey) || mapKey.includes(key)) return asset;
  }
  return null;
}

/**
 * Check if an exercise has a 3D model available.
 */
export function hasExerciseModel(exerciseName: string): boolean {
  return getExerciseModel(exerciseName) !== null;
}
