-- Workout plans (generated by Claude)
create table if not exists workout_plans (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  plan jsonb not null,
  created_at timestamptz default now() not null
);

alter table workout_plans enable row level security;

create policy "Users can manage their own plans"
  on workout_plans for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Workout logs (user-logged sets)
create table if not exists workout_logs (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  plan_id uuid references workout_plans(id) on delete set null,
  day_name text not null,
  exercises jsonb not null,
  completed_at timestamptz default now() not null
);

alter table workout_logs enable row level security;

create policy "Users can manage their own logs"
  on workout_logs for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
